version: "3"
services:
  voicetext:
    build: .
    # image: python:3.7
    # command: pip3 install flask requests
    tty: true
    stdin_open: true
    volumes:
      - ./src:/src
    ports:
      - 5000:5000
